name: On push workflow

on:
  push:
    branches: '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11.2
      uses: actions/setup-python@v1
      with:
        python-version: 3.11.2
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./web/requirements.txt
    - name: Run Tests'
      env:
        SECRET_KEY: 69tgugtg%^fgJwerqO&*&
        DJANGO_ALLOWED_HOSTS: localhost 127.0.0.1 [::1]
        DEBUG_MODE: False
      run: |
        python manage.py test